#!/usr/bin/env bash
# Collect read-only ROS 2 information needed to build the dual-PiPER Bunker URDF.
# This script does not publish commands or move the chassis/arms.

set -u

STAMP="$(date +%Y%m%d_%H%M%S)"
OUTPUT_DIR="${1:-$PWD/bunker_piper_diagnostics_$STAMP}"
mkdir -p "$OUTPUT_DIR"

if ! command -v ros2 >/dev/null 2>&1; then
  if [ -f /opt/ros/humble/setup.bash ]; then
    # shellcheck disable=SC1091
    source /opt/ros/humble/setup.bash
  fi
fi

for workspace_setup in /ros2_ws/install/setup.bash "$HOME/ros2_ws/install/setup.bash"; do
  if [ -f "$workspace_setup" ]; then
    # shellcheck disable=SC1090
    source "$workspace_setup"
  fi
done

if ! command -v ros2 >/dev/null 2>&1; then
  echo "ERROR: ros2 was not found. Run this inside the configured ROS 2 container or source the workspace first." >&2
  exit 1
fi

run_capture() {
  local filename="$1"
  shift
  {
    echo "COMMAND: $*"
    echo "TIME: $(date --iso-8601=seconds)"
    echo
    "$@"
  } >"$OUTPUT_DIR/$filename" 2>&1 || true
}

safe_echo_once() {
  local topic="$1"
  local safe_name
  safe_name="$(printf '%s' "$topic" | sed 's#^/##; s#[^A-Za-z0-9_.-]#_#g')"
  timeout 8s ros2 topic info "$topic" -v >"$OUTPUT_DIR/topic_${safe_name}_info.txt" 2>&1 || true
  timeout 8s ros2 topic echo "$topic" --once >"$OUTPUT_DIR/topic_${safe_name}_sample.txt" 2>&1 || true
}

run_capture ros_distro.txt bash -lc 'printf "ROS_DISTRO=%s\nROS_DOMAIN_ID=%s\nRMW_IMPLEMENTATION=%s\n" "${ROS_DISTRO:-}" "${ROS_DOMAIN_ID:-}" "${RMW_IMPLEMENTATION:-}"'
run_capture nodes.txt ros2 node list
run_capture topics_with_types.txt ros2 topic list -t
run_capture services.txt ros2 service list -t
run_capture actions.txt ros2 action list -t
run_capture packages_relevant.txt bash -lc "ros2 pkg list | grep -Ei 'bunker|piper|realsense|rtabmap|robot_localization|nav2|robot_state|joint_state'"

if command -v ip >/dev/null 2>&1; then
  run_capture network_links.txt ip -br link
  run_capture can_links.txt bash -lc "ip -details link show type can"
fi

mapfile -t TOPICS < <(ros2 topic list 2>/dev/null)
for topic in "${TOPICS[@]}"; do
  case "$topic" in
    *joint_state*|*/odom|*/odometry*|*/camera_info|*/imu|*/imu/*|/robot_description)
      safe_echo_once "$topic"
      ;;
  esac
done

for topic in /tf /tf_static; do
  if printf '%s\n' "${TOPICS[@]}" | grep -Fxq "$topic"; then
    safe_echo_once "$topic"
  fi
done

for pair in "map odom" "odom base_link" "base_link front_camera_color_optical_frame" "base_link rear_camera_color_optical_frame"; do
  parent="${pair%% *}"
  child="${pair#* }"
  safe_pair="${parent}_to_${child}"
  timeout 6s ros2 run tf2_ros tf2_echo "$parent" "$child" >"$OUTPUT_DIR/tf_${safe_pair}.txt" 2>&1 || true
done

if ros2 pkg prefix tf2_tools >/dev/null 2>&1; then
  (
    cd "$OUTPUT_DIR" || exit 1
    timeout 20s ros2 run tf2_tools view_frames >view_frames_log.txt 2>&1 || true
  )
fi

for package in bunker_base piper_description realsense2_camera rtabmap_slam robot_state_publisher nav2_bringup; do
  ros2 pkg prefix "$package" >"$OUTPUT_DIR/package_${package}.txt" 2>&1 || true
done

cat >"$OUTPUT_DIR/README.txt" <<EOF
Bunker + dual-PiPER URDF diagnostic bundle
Created: $(date --iso-8601=seconds)

Please send this entire directory (zip it if convenient), including any frames PDF generated by tf2_tools.
The collector only reads ROS, TF, CAN-interface and package information. It does not publish motion commands.
EOF

echo "Collection complete: $OUTPUT_DIR"
echo "Please zip and send the entire directory."
