map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: /ros2_ws/src/bunker_slam_bringup/maps/bunker_map.yaml

amcl:
  ros__parameters:
    use_sim_time: false
    global_frame_id: map
    odom_frame_id: odom
    base_frame_id: base_link
    scan_topic: /scan
    tf_broadcast: true
    transform_tolerance: 0.5
    set_initial_pose: false
    always_reset_initial_pose: false
    first_map_only: false
    save_pose_rate: 0.5

    min_particles: 500
    max_particles: 2000
    kld_err: 0.05
    kld_z: 0.99
    update_min_d: 0.05
    update_min_a: 0.05
    resample_interval: 1

    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    laser_model_type: likelihood_field
    laser_likelihood_max_dist: 2.0
    laser_max_range: 8.0
    laser_min_range: 0.15
    max_beams: 60
    z_hit: 0.5
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.5
    sigma_hit: 0.2
    lambda_short: 0.1

    robot_model_type: nav2_amcl::DifferentialMotionModel

