services:
  trystan-bunker-navigation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: trystan-bunker-navigation:nav-man
    container_name: trystan-bunker-navigation
    network_mode: host
    privileged: true
    ipc: host
    environment:
      DISPLAY: ${DISPLAY:-:1}
      QT_X11_NO_MITSHM: "1"
      QT_QPA_PLATFORM: xcb
      ROS_DOMAIN_ID: "173"
      ROS_LOCALHOST_ONLY: "1"
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../:/ros2_ws/src/bunker-piper_integration:rw
      - nav_man_maps:/ros2_ws/maps
    stdin_open: true
    tty: true

volumes:
  nav_man_maps:
